# Generated by Django 5.1 on 2024-09-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_moodentry_quantity_alter_moodentry_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodentry',
            name='description',
        ),
        migrations.AddField(
            model_name='moodentry',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
