# Generated by Django 5.1 on 2024-09-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_moodentry_description_moodentry_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoodEntry',
            new_name='BookEntry',
        ),
    ]
