# Generated by Django 5.1 on 2024-09-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_moodentry_bookentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookentry',
            name='quantity',
        ),
        migrations.AddField(
            model_name='bookentry',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
