# Generated by Django 5.1 on 2024-09-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_bookentry_quantity_bookentry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookentry',
            name='image',
            field=models.ImageField(default="upload_to='images/', default='images/default.jpg'", upload_to=''),
        ),
    ]
