# Generated by Django 5.1 on 2024-09-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_bookentry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookentry',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
